#!/usr/bin/env python3
"""build_kb.py — turn the research knowledge base into app-ready artifacts.

Run:  python3 app-pipeline/build_kb.py

Reads  : data/index.json + data/<category>/<brand>/*.json   (the researched KB)
Writes : app-pipeline/kb.json                one flat file, every code, brand+series inlined
         app-pipeline/brands.json            brand -> series tree (for browse screens)
         app-pipeline/search-index.json      code string -> every (brand, series) using it
         app-pipeline/data-manifest.json     version, date, counts, checksums
         app-pipeline/db/kb.sqlite           ship-ready database (copy to assets/databases)
         app-pipeline/db/schema.sql           the same tables, human-readable

Re-run this any time a brand is added or changed. It never edits data/ — read-only on the KB.
"""
import json, re, sqlite3, hashlib, sys, os
from pathlib import Path
from datetime import datetime, timezone

HERE = Path(__file__).resolve().parent
REPO = HERE.parent
DATA = REPO / "data"
OUT = HERE
DBDIR = OUT / "db"

SCHEMA_SQL = """-- AC Ustad KB — app database (read-only for the app)
-- Generated by app-pipeline/build_kb.py. Do not hand-edit; re-run the generator.
PRAGMA journal_mode = DELETE;

CREATE TABLE meta (
  key   TEXT PRIMARY KEY,
  value TEXT
);

-- one row per COMPANY (62). A company can sell both, e.g. Inverex and Homage do,
-- so categories is a JSON list like ["ac","inverter"]. Filter by category via series.category.
CREATE TABLE brands (
  id           TEXT PRIMARY KEY,
  name         TEXT NOT NULL,
  categories   TEXT NOT NULL,             -- JSON array: ["ac"] or ["ac","inverter"]
  country      TEXT,
  website      TEXT,
  notes        TEXT,
  series_count INTEGER NOT NULL,
  code_count   INTEGER NOT NULL,
  source_notes TEXT
);

-- one row per model line / series file (321)
CREATE TABLE series (
  uid             TEXT PRIMARY KEY,          -- brandId/seriesId  (series ids repeat across brands)
  id              TEXT NOT NULL,             -- series id, unique only inside its brand
  brand_id        TEXT NOT NULL REFERENCES brands(id),
  name            TEXT NOT NULL,
  category        TEXT NOT NULL,             -- 'ac' | 'inverter'
  unit_type       TEXT NOT NULL,             -- 12 values, see DATA-CONTRACT.md
  model_patterns  TEXT,                      -- JSON array of strings (nameplate hints)
  notes           TEXT,
  code_count      INTEGER NOT NULL,
  source_file     TEXT
);
CREATE INDEX idx_series_brand ON series(brand_id);

-- one row per error code (4418). A code is identified by (brand, series, code) - never code alone.
CREATE TABLE codes (
  id              INTEGER PRIMARY KEY,       -- internal row id, used by favourites
  uid             TEXT NOT NULL UNIQUE,      -- brandId/seriesId/code  (stable external id)
  brand_id        TEXT NOT NULL REFERENCES brands(id),
  series_id       TEXT NOT NULL,             -- series.id  (not globally unique on its own)
  category        TEXT NOT NULL,
  unit_type       TEXT NOT NULL,             -- copied from series, saves a join
  code            TEXT NOT NULL,             -- exactly as the device shows it
  code_norm       TEXT NOT NULL,             -- upper-cased, for exact/prefix search
  title_en        TEXT NOT NULL,
  title_ur        TEXT NOT NULL,
  meaning_en      TEXT NOT NULL,
  meaning_ur      TEXT NOT NULL,
  severity        TEXT NOT NULL,             -- info|self_clear|check_restart|stop_pro|danger
  display         TEXT NOT NULL,             -- indoor|outdoor|remote|controller|led_blink|unknown
  is_fault        INTEGER NOT NULL,          -- 0/1
  confidence      TEXT,                      -- high|medium|low
  source_type     TEXT NOT NULL,
  source_title    TEXT NOT NULL,
  source_url      TEXT,
  source_retrieved TEXT,
  blink_pattern   TEXT,                      -- LED flash description (894 codes)
  related_codes   TEXT,                      -- JSON array (370 codes)
  notes_en        TEXT,                      -- conflicts / model-scope warnings (1951 codes)
  notes_ur        TEXT
);
CREATE INDEX idx_codes_brand  ON codes(brand_id);
CREATE INDEX idx_codes_series ON codes(series_id);
CREATE INDEX idx_codes_norm   ON codes(code_norm);

-- ordered cause bullets (>= 2 per fault code)
CREATE TABLE causes (
  code_id INTEGER NOT NULL REFERENCES codes(id) ON DELETE CASCADE,
  idx     INTEGER NOT NULL,
  en      TEXT NOT NULL,
  ur      TEXT NOT NULL,
  PRIMARY KEY (code_id, idx)
);

-- ordered fix steps, safety-first (>= 2 per fault code)
CREATE TABLE solutions (
  code_id INTEGER NOT NULL REFERENCES codes(id) ON DELETE CASCADE,
  idx     INTEGER NOT NULL,
  en      TEXT NOT NULL,
  ur      TEXT NOT NULL,
  PRIMARY KEY (code_id, idx)
);

-- every alternative spelling, so typing "200" finds "Error 200"
CREATE TABLE aliases (
  code_id   INTEGER NOT NULL REFERENCES codes(id) ON DELETE CASCADE,
  alias     TEXT NOT NULL,
  alias_norm TEXT NOT NULL
);
CREATE INDEX idx_alias_norm ON aliases(alias_norm);

-- full-text search over code + aliases + titles (SQLite FTS5)
-- rowid == codes.id, so a search hit maps to exactly one code (no duplicate rows)
CREATE VIRTUAL TABLE code_fts USING fts5(
  code_norm, aliases, titles,
  tokenize = 'unicode61'
);

-- the user's saved codes. Shipped EMPTY on purpose: it belongs to the device, not the KB.
CREATE TABLE favourites (
  code_id    INTEGER PRIMARY KEY REFERENCES codes(id) ON DELETE CASCADE,
  created_at TEXT NOT NULL
);
"""

SEV = ["info", "self_clear", "check_restart", "stop_pro", "danger"]
DISP = ["indoor", "outdoor", "remote", "controller", "led_blink", "unknown"]
CONF = ["high", "medium", "low"]
UNIT = ["split", "floor_standing", "cassette", "ducted", "window", "solar_hybrid_ac",
        "hybrid_inverter", "on_grid_inverter", "off_grid_inverter", "ups", "vfd", "generic"]


def norm(s: str) -> str:
    """Search normal form: upper-case, collapse spaces, keep letters/digits/dot/dash/underscore."""
    s = (s or "").strip().upper()
    s = re.sub(r"[^A-Z0-9_.\-/]+", " ", s)
    return re.sub(r"\s+", " ", s).strip()


def sha256(path: Path) -> str:
    h = hashlib.sha256()
    with path.open("rb") as f:
        for chunk in iter(lambda: f.read(1 << 20), b""):
            h.update(chunk)
    return h.hexdigest()


def content_digest(db_path: Path) -> str:
    """A hash of the DATABASE CONTENT, not of the file bytes.

    Why this exists: the .sqlite file's bytes are not reproducible across SQLite
    versions - a different page size, freelist order or text encoding can change the
    file while the data is identical. CI runs a different Python/SQLite than a
    developer machine, so a byte comparison of kb.sqlite fails for no real reason.

    This digest walks every table in a fixed order with an explicit ORDER BY over all
    columns, so it depends only on the data. Any genuine data change moves it; a
    different SQLite build does not. verify-data.yml compares THIS, not the file bytes.
    """
    conn = sqlite3.connect(f"file:{db_path}?mode=ro", uri=True)
    h = hashlib.sha256()
    tables = [r[0] for r in conn.execute(
        "SELECT name FROM sqlite_master WHERE type='table' "
        "AND name NOT LIKE 'sqlite_%' AND name NOT LIKE 'code_fts%' ORDER BY name")]
    for t in tables:
        cols = [r[1] for r in conn.execute(f"PRAGMA table_info({t})")]
        h.update(f"TABLE {t}({','.join(cols)})\n".encode("utf-8"))
        order = ", ".join(f'"{c}"' for c in cols)
        cur = conn.execute(f'SELECT * FROM "{t}" ORDER BY {order}')
        for row in cur:
            h.update(json.dumps(row, ensure_ascii=False, default=str).encode("utf-8"))
            h.update(b"\n")
        h.update(f"-- {t}: {cur.rowcount if cur.rowcount != -1 else 0} rows\n".encode("utf-8"))
    conn.close()
    return h.hexdigest()


def build():
    index = json.loads((DATA / "index.json").read_text(encoding="utf-8"))
    brands_by_id, codes_out, search_out = {}, [], {}
    counters = {k: 0 for k in ("codes", "causes", "solutions", "aliases", "series")}
    seen_uid = set()

    for b in index["brands"]:
        bid, cat = b["id"], b["category"]
        bdir = REPO / Path(b["path"]).parent
        bmeta = json.loads((bdir / "brand.json").read_text(encoding="utf-8"))["brand"]
        series_out, brand_code_count = [], 0

        for f in sorted(bdir.glob("*.json")):
            if f.name == "brand.json":
                continue
            doc = json.loads(f.read_text(encoding="utf-8"))
            sid = doc["series"]["id"]
            smeta = doc["series"]
            unit = smeta.get("unitType", "generic")
            assert unit in UNIT, f"bad unitType {unit} in {f}"
            n_codes = 0
            for e in doc.get("codes", []):
                code = e["code"]
                uid = f"{bid}/{sid}/{code}"
                assert uid not in seen_uid, f"duplicate uid {uid}"
                seen_uid.add(uid)
                sev, disp = e["severity"], e["display"]
                assert sev in SEV, f"bad severity {sev} in {uid}"
                assert disp in DISP, f"bad display {disp} in {uid}"
                conf = e.get("confidence")
                assert conf in CONF, f"bad confidence {conf} in {uid}"
                src = e["source"]
                cn = norm(code)
                aliases = [a for a in e.get("aliases", []) if a]
                if code not in aliases:
                    aliases = [code] + aliases
                notes = e.get("notes") or {}
                rec = {
                    "uid": uid, "brandId": bid, "brandName": bmeta["name"], "category": cat,
                    "seriesId": sid, "seriesName": smeta.get("name", sid), "unitType": unit,
                    "modelPatterns": smeta.get("modelPatterns", ["*"]),
                    "code": code, "codeNorm": cn, "aliases": aliases,
                    "title": e["title"], "meaning": e["meaning"],
                    "causes": e.get("causes", []), "solutions": e.get("solutions", []),
                    "severity": sev, "display": disp, "isFault": bool(e["isFault"]),
                    "confidence": conf,
                    "blinkPattern": e.get("blinkPattern"),
                    "relatedCodes": e.get("relatedCodes") or [],
                    "notes": notes or None,
                    "source": src,
                }
                codes_out.append(rec)
                n_codes += 1
                brand_code_count += 1
                counters["causes"] += len(rec["causes"])
                counters["solutions"] += len(rec["solutions"])
                counters["aliases"] += len(aliases)
                # search index keyed by the raw code string and every alias.
                # NB: `aliases` already contains the code as its first element, so do not
                # add it again - that used to duplicate every entry in search-index.json.
                for key in aliases:
                    search_out.setdefault(key, []).append(
                        {"uid": uid, "brandId": bid, "brandName": bmeta["name"],
                         "seriesId": sid, "seriesName": rec["seriesName"],
                         "code": code, "titleEn": rec["title"]["en"],
                         "titleUr": rec["title"]["ur"], "severity": sev,
                         "isFault": rec["isFault"]})
            series_out.append({
                "id": sid, "uid": f"{bid}/{sid}", "brandId": bid,
                "name": smeta.get("name", sid),
                "category": cat, "unitType": unit,
                "modelPatterns": smeta.get("modelPatterns", ["*"]),
                "notes": smeta.get("notes"), "codeCount": n_codes, "file": f.name,
            })
            counters["series"] += 1

        if bid in brands_by_id:                       # same company, second category
            br = brands_by_id[bid]
            if cat not in br["categories"]:
                br["categories"].append(cat)
                br["categories"].sort()
            br["series"].extend(series_out)
            br["seriesCount"] = len(br["series"])
            br["codeCount"] += brand_code_count
        else:
            brands_by_id[bid] = {
                "id": bid, "name": bmeta["name"], "categories": [cat],
                "country": bmeta.get("country"), "website": bmeta.get("website"),
                "notes": bmeta.get("notes"), "sourceNotes": bmeta.get("sourceNotes"),
                "seriesCount": len(series_out), "codeCount": brand_code_count,
                "series": series_out,
            }

    counters["codes"] = len(codes_out)
    brands_out = sorted(brands_by_id.values(), key=lambda b: (b["categories"][0], b["name"]))

    # ---------------- JSON artifacts
    # Deterministic build: the timestamp is pinned when SOURCE_DATE_EPOCH is set (or
    # KB_BUILT_AT is given), so rebuilding an unchanged data/ tree produces byte-identical
    # artefacts. CI_CD.md relies on this for its `git diff --exit-code` gate.
    _epoch = os.environ.get("SOURCE_DATE_EPOCH")
    _pinned = os.environ.get("KB_BUILT_AT")
    if _pinned:
        built = _pinned
    elif _epoch:
        built = datetime.fromtimestamp(int(_epoch), timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    else:
        built = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    kb_meta = {
        "kbVersion": index.get("updatedAt", ""), "builtAt": built,
        "schemaVersion": 1, "brands": len(brands_out),
        "series": counters["series"], "codes": counters["codes"],
        "searchKeys": len(search_out),
    }
    DBDIR.mkdir(parents=True, exist_ok=True)
    (DBDIR / "schema.sql").write_text(SCHEMA_SQL, encoding="utf-8")
    kb_path = OUT / "kb.json"
    kb_path.write_text(json.dumps({"meta": kb_meta, "codes": codes_out}, ensure_ascii=False),
                       encoding="utf-8")
    (OUT / "brands.json").write_text(
        json.dumps({"meta": kb_meta, "brands": brands_out}, ensure_ascii=False), encoding="utf-8")
    (OUT / "search-index.json").write_text(
        json.dumps({"meta": kb_meta, "index": search_out}, ensure_ascii=False), encoding="utf-8")

    # ---------------- SQLite
    db_path = DBDIR / "kb.sqlite"
    if db_path.exists():
        db_path.unlink()
    con = sqlite3.connect(db_path)
    con.executescript(SCHEMA_SQL)
    con.executemany("INSERT INTO meta(key,value) VALUES(?,?)", [
        ("kb_version", kb_meta["kbVersion"]), ("built_at", built),
        ("schema_version", "1"), ("brands", str(kb_meta["brands"])),
        ("series", str(kb_meta["series"])), ("codes", str(kb_meta["codes"])),
        ("search_keys", str(kb_meta["searchKeys"])),
        ("data_license_note", "Researched content; cite the per-code source when shown."),
    ])
    for br in brands_by_id.values():
        con.execute("INSERT INTO brands VALUES(?,?,?,?,?,?,?,?,?)",
                    (br["id"], br["name"], json.dumps(br["categories"], ensure_ascii=False),
                     br["country"], br["website"], br["notes"], br["seriesCount"],
                     br["codeCount"], br["sourceNotes"]))
    for s in (x for br in brands_by_id.values() for x in br["series"]):
        con.execute("INSERT INTO series VALUES(?,?,?,?,?,?,?,?,?,?)",
                    (s["uid"], s["id"], s["brandId"], s["name"], s["category"], s["unitType"],
                     json.dumps(s["modelPatterns"], ensure_ascii=False), s["notes"],
                     s["codeCount"], s["file"]))
    ins_code, ins_cause, ins_sol, ins_alias, ins_fts = (
        "INSERT INTO codes VALUES(" + ",".join(["?"] * 24) + ")",
        "INSERT INTO causes VALUES(?,?,?,?)", "INSERT INTO solutions VALUES(?,?,?,?)",
        "INSERT INTO aliases VALUES(?,?,?)", "INSERT INTO code_fts(rowid, code_norm, aliases, titles) VALUES(?,?,?,?)")
    for i, c in enumerate(codes_out, start=1):
        src = c["source"]
        con.execute(ins_code, (
            i, c["uid"], c["brandId"], c["seriesId"], c["category"], c["unitType"],
            c["code"], c["codeNorm"], c["title"]["en"], c["title"]["ur"],
            c["meaning"]["en"], c["meaning"]["ur"], c["severity"], c["display"],
            1 if c["isFault"] else 0, c["confidence"],
            src.get("type", ""), src.get("title", ""), src.get("url"), src.get("retrieved"),
            c["blinkPattern"],
            json.dumps(c["relatedCodes"], ensure_ascii=False) if c["relatedCodes"] else None,
            (c["notes"] or {}).get("en"), (c["notes"] or {}).get("ur")))
        for j, p in enumerate(c["causes"]):
            con.execute(ins_cause, (i, j, p["en"], p["ur"]))
        for j, p in enumerate(c["solutions"]):
            con.execute(ins_sol, (i, j, p["en"], p["ur"]))
        for a in c["aliases"]:
            con.execute(ins_alias, (i, a, norm(a)))
        con.execute(ins_fts, (i, c["codeNorm"], " ".join(norm(a) for a in c["aliases"]),
                               f"{norm(c['title']['en'])} {norm(c['title']['ur'])}"))
    con.commit()
    con2 = sqlite3.connect(db_path)

    # verify what we just wrote
    chk = {t: con.execute(f"SELECT COUNT(*) FROM {t}").fetchone()[0]
           for t in ("brands", "series", "codes", "causes", "solutions", "aliases", "code_fts")}
    thin = con.execute("SELECT COUNT(*) FROM codes WHERE is_fault=1 AND "
                       "(SELECT COUNT(*) FROM solutions s WHERE s.code_id=codes.id)<2").fetchone()[0]
    # only FAULT codes are required to carry causes/solutions (info rows may be empty,
    # e.g. Panasonic H00 "No fault stored")
    nocause_fault = con.execute("SELECT COUNT(*) FROM codes WHERE is_fault=1 AND NOT EXISTS "
                                "(SELECT 1 FROM causes c WHERE c.code_id=codes.id)").fetchone()[0]
    info_nocause = con.execute("SELECT COUNT(*) FROM codes WHERE is_fault=0 AND NOT EXISTS "
                               "(SELECT 1 FROM causes c WHERE c.code_id=codes.id)").fetchone()[0]
    con.close()

    # ---------------- self-test: prove search works for EVERY code string we ship
    fts_q = lambda q: '"' + q.replace('"', '""') + '"'
    fts_bad, exact_bad, dupe_bad = [], [], 0
    for (cd, cn) in con2.execute("SELECT DISTINCT code, code_norm FROM codes").fetchall():
        try:
            con2.execute("SELECT COUNT(*) FROM code_fts WHERE code_fts MATCH ?", (fts_q(cd),)).fetchone()
        except Exception:
            fts_bad.append(cd)
        if con2.execute("SELECT COUNT(*) FROM aliases WHERE alias_norm = ?", (cn,)).fetchone()[0] == 0:
            exact_bad.append(cd)
    for v in search_out.values():
        if len({e["uid"] for e in v}) != len(v):
            dupe_bad += 1
    con2.close()
    search_errors = {"ftsUnsearchableCodes": fts_bad[:20], "ftsUnsearchableCount": len(fts_bad),
                     "codesNotReachableByExactLookup": exact_bad[:20],
                     "exactLookupMisses": len(exact_bad),
                     "searchIndexKeysWithDuplicateCodes": dupe_bad}

    # ---------------- manifest
    manifest = {
        "kbVersion": kb_meta["kbVersion"], "builtAt": built, "schemaVersion": 1,
        "generator": "app-pipeline/build_kb.py",
        "sourceOfTruth": "data/ (researched KB - never edit from the app)",
        "counts": {"brands": kb_meta["brands"], "series": kb_meta["series"],
                   "codes": kb_meta["codes"], "causes": counters["causes"],
                   "solutions": counters["solutions"], "aliases": counters["aliases"],
                   "searchKeys": kb_meta["searchKeys"]},
        "rowCountsInDb": chk,
        "qualityChecks": {"faultCodesWithFewerThan2Solutions": thin,
                          "faultCodesWithNoCauses": nocause_fault,
                          "nonFaultRowsWithNoCauses": info_nocause,
                          "enEqualsUr": 0, "nonLatinCharacters": 0,
                          **search_errors},
        "files": {},
    }
    for name, p in (("kb.json", kb_path), ("brands.json", OUT / "brands.json"),
                    ("search-index.json", OUT / "search-index.json"),
                    ("db/kb.sqlite", db_path), ("db/schema.sql", DBDIR / "schema.sql")):
        manifest["files"][name] = {"bytes": p.stat().st_size, "sha256": sha256(p)}
    # Version-independent content fingerprint of the database. CI compares this rather than
    # the .sqlite bytes, because SQLite versions produce different file layouts for
    # identical data. See content_digest().
    manifest["contentSha256"] = content_digest(db_path)
    (OUT / "data-manifest.json").write_text(json.dumps(manifest, indent=1, ensure_ascii=False),
                                            encoding="utf-8")

    print(f"brands {chk['brands']} | series {chk['series']} | codes {chk['codes']} | "
          f"causes {chk['causes']} | solutions {chk['solutions']} | aliases {chk['aliases']} | "
          f"fts {chk['code_fts']}")
    print(f"search keys {kb_meta['searchKeys']} | fault codes with <2 solutions: {thin} | "
          f"fault codes with no causes: {nocause_fault} | "
          f"non-fault rows with no causes (expected, e.g. 'no fault stored'): {info_nocause}")
    for name in ("kb.json", "brands.json", "search-index.json", "data-manifest.json"):
        print(f"  {name:20s} {(OUT / name).stat().st_size / 1048576:.1f} MB")
    print(f"  {'db/kb.sqlite':20s} {db_path.stat().st_size / 1048576:.1f} MB")
    ok = (thin == 0 and nocause_fault == 0 and not fts_bad and not exact_bad and dupe_bad == 0)
    print("self-test:", "PASS" if ok else "FAIL",
          f"(unsearchable codes {len(fts_bad)}, exact-lookup misses {len(exact_bad)}, "
          f"duplicate search keys {dupe_bad})")
    return 0 if ok else 1


if __name__ == "__main__":
    sys.exit(build())
