-- AC Ustad KB — app database (read-only for the app)
-- Generated by app-pipeline/build_kb.py. Do not hand-edit; re-run the generator.
PRAGMA journal_mode = DELETE;

CREATE TABLE meta (
  key   TEXT PRIMARY KEY,
  value TEXT
);

-- one row per COMPANY (62). A company can sell both, e.g. Inverex and Homage do,
-- so categories is a JSON list like ["ac","inverter"]. Filter by category via series.category.
CREATE TABLE brands (
  id           TEXT PRIMARY KEY,
  name         TEXT NOT NULL,
  categories   TEXT NOT NULL,             -- JSON array: ["ac"] or ["ac","inverter"]
  country      TEXT,
  website      TEXT,
  notes        TEXT,
  series_count INTEGER NOT NULL,
  code_count   INTEGER NOT NULL,
  source_notes TEXT
);

-- one row per model line / series file (321)
CREATE TABLE series (
  uid             TEXT PRIMARY KEY,          -- brandId/seriesId  (series ids repeat across brands)
  id              TEXT NOT NULL,             -- series id, unique only inside its brand
  brand_id        TEXT NOT NULL REFERENCES brands(id),
  name            TEXT NOT NULL,
  category        TEXT NOT NULL,             -- 'ac' | 'inverter'
  unit_type       TEXT NOT NULL,             -- 12 values, see DATA-CONTRACT.md
  model_patterns  TEXT,                      -- JSON array of strings (nameplate hints)
  notes           TEXT,
  code_count      INTEGER NOT NULL,
  source_file     TEXT
);
CREATE INDEX idx_series_brand ON series(brand_id);

-- one row per error code (4418). A code is identified by (brand, series, code) - never code alone.
CREATE TABLE codes (
  id              INTEGER PRIMARY KEY,       -- internal row id, used by favourites
  uid             TEXT NOT NULL UNIQUE,      -- brandId/seriesId/code  (stable external id)
  brand_id        TEXT NOT NULL REFERENCES brands(id),
  series_id       TEXT NOT NULL,             -- series.id  (not globally unique on its own)
  category        TEXT NOT NULL,
  unit_type       TEXT NOT NULL,             -- copied from series, saves a join
  code            TEXT NOT NULL,             -- exactly as the device shows it
  code_norm       TEXT NOT NULL,             -- upper-cased, for exact/prefix search
  title_en        TEXT NOT NULL,
  title_ur        TEXT NOT NULL,
  meaning_en      TEXT NOT NULL,
  meaning_ur      TEXT NOT NULL,
  severity        TEXT NOT NULL,             -- info|self_clear|check_restart|stop_pro|danger
  display         TEXT NOT NULL,             -- indoor|outdoor|remote|controller|led_blink|unknown
  is_fault        INTEGER NOT NULL,          -- 0/1
  confidence      TEXT,                      -- high|medium|low
  source_type     TEXT NOT NULL,
  source_title    TEXT NOT NULL,
  source_url      TEXT,
  source_retrieved TEXT,
  blink_pattern   TEXT,                      -- LED flash description (894 codes)
  related_codes   TEXT,                      -- JSON array (370 codes)
  notes_en        TEXT,                      -- conflicts / model-scope warnings (1951 codes)
  notes_ur        TEXT
);
CREATE INDEX idx_codes_brand  ON codes(brand_id);
CREATE INDEX idx_codes_series ON codes(series_id);
CREATE INDEX idx_codes_norm   ON codes(code_norm);

-- ordered cause bullets (>= 2 per fault code)
CREATE TABLE causes (
  code_id INTEGER NOT NULL REFERENCES codes(id) ON DELETE CASCADE,
  idx     INTEGER NOT NULL,
  en      TEXT NOT NULL,
  ur      TEXT NOT NULL,
  PRIMARY KEY (code_id, idx)
);

-- ordered fix steps, safety-first (>= 2 per fault code)
CREATE TABLE solutions (
  code_id INTEGER NOT NULL REFERENCES codes(id) ON DELETE CASCADE,
  idx     INTEGER NOT NULL,
  en      TEXT NOT NULL,
  ur      TEXT NOT NULL,
  PRIMARY KEY (code_id, idx)
);

-- every alternative spelling, so typing "200" finds "Error 200"
CREATE TABLE aliases (
  code_id   INTEGER NOT NULL REFERENCES codes(id) ON DELETE CASCADE,
  alias     TEXT NOT NULL,
  alias_norm TEXT NOT NULL
);
CREATE INDEX idx_alias_norm ON aliases(alias_norm);

-- full-text search over code + aliases + titles (SQLite FTS5)
-- rowid == codes.id, so a search hit maps to exactly one code (no duplicate rows)
CREATE VIRTUAL TABLE code_fts USING fts5(
  code_norm, aliases, titles,
  tokenize = 'unicode61'
);

-- the user's saved codes. Shipped EMPTY on purpose: it belongs to the device, not the KB.
CREATE TABLE favourites (
  code_id    INTEGER PRIMARY KEY REFERENCES codes(id) ON DELETE CASCADE,
  created_at TEXT NOT NULL
);
